language: ruby
cache: bundler
dist: trusty

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem --version
    # travis may preinstall a bundler gem which is later than the one which we pin, which may totally hose us, so we preemtively
    # uninstall anything they may have installed here.  if they haven't installed anything then we have to ignore the failure
    # to uninstall the default bundler that ships embedded in ruby itself.
  - rvm @global do gem uninstall bundler -a -x || true
  - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
  - bundle --version
  - rm -f .bundle/config

before_script:
 # force all .rspec tests into progress display to reduce line count
 - echo --color > .rspec
 - echo -fp >> .rspec
 # necessary for sudo: true tests, ingore failures on tests invoked with sudo: false
 - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master
  - chef-14

env:
  global:
    - FORCE_FFI_YAJL=ext
    - CHEF_LICENSE="accept-no-persist"

matrix:
  include:
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-amazonlinux-2
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - AMAZON=2
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-amazonlinux
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - AMAZON=201X
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-ubuntu-1604
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=16.04
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-ubuntu-1804
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=18.04
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-debian-8
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - DEBIAN=8
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-debian-9
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - DEBIAN=9
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-debian-10
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - DEBIAN=10
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-centos-6
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - CENTOS=6
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-centos-7
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - CENTOS=7
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-fedora-latest
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - FEDORA=latest
      - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    services: docker
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test end-to-end-opensuse-leap
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
     - OPENSUSELEAP=42
     - KITCHEN_YAML=kitchen.yml
  - rvm: 2.5.5
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - rvm @global do gem uninstall bundler -a -x || true
      - gem install bundler -v $(grep :bundler omnibus_overrides.rb | cut -d'"' -f2)
      - sudo apt-get update
      - sudo apt-get -y install squid3 git curl
    env:
      - PROXY_TESTS_DIR=proxy_tests/files/default/scripts
      - PROXY_TESTS_REPO=$PROXY_TESTS_DIR/repo
    script:
      - bundle exec chef-client --version
      - git clone https://github.com/chef/proxy_tests.git
      - rvmsudo -E bundle exec bash $PROXY_TESTS_DIR/run_tests.sh chef_client \* \* /tmp/out.txt
    after_script:
      - cat /tmp/out.txt
      - sudo cat /var/log/squid3/cache.log
      - sudo cat /var/log/squid3/access.log

notifications:
  on_change: true
  on_failure: true
  on_success: change
  on_pull_requests: false
